### ISSUE TITLE
Delete All Paths doesn't work in Glyphs 3

### ISSUE THREAD

**Issue by elenage** [kylewaynebenson/Glyphs-Scripts#5]
Any chance to get this fixed?
This is what Macro window says:
Traceback (most recent call last):
  File "DeleteAllPaths.py", line 32
    deleteSmallestPath( thisLayer )
  File "DeleteAllPaths.py", line 25, in deleteSmallestPath
    thisLayer.removePathAtIndex_( thatIndex )
AttributeError: 'NSKVONotifying_GSLayer' object has no attribute 'removePathAtIndex_'

**Comment by RafalBuchner** [comment]
I think it should work now, could you check it out?
