### ISSUE TITLE
GlyphsApp team would like to collaborate on maintaining those scripts

### ISSUE THREAD

**Issue by RafalBuchner** [kylewaynebenson/Glyphs-Scripts#6]
@kylewaynebenson 
Hi, me and @mekkablue (we both work for GlyphsApp) would love to help maintain your scripts for the Glyphs 3 update. Could you add us as contributors for this repository?

**Comment by kylewaynebenson** [comment]
@RafalBuchner @mekkablue
Would love all the help I can get! I've been dipping in and out of Glyphs 3—the scripts are one of the reasons I haven't fully transferred over.
