### ISSUE TITLE
LocalGuidelines functional question

### ISSUE THREAD

**Issue by RafalBuchner** [kylewaynebenson/Glyphs-Scripts#7]
@kylewaynebenson, could you explain a bit what the LocalGuidelines.py script should do?

Correct me if I'm wrong:
1. you want to parse through glyphs in search of glyphs with some extension (e.g. `g.alt`)
2. then you take each local guideline in this glyph and you send (copy) it to base glyph ( if we pull the `g.alt` then it is being send to `g`), right?

I see that this is not finished, I could rewrite it to work in both G2 and G3 apps

**Comment by kylewaynebenson** [comment]
@RafalBuchner, I really should turn on some email notifications for github issues! I'll admit, I do not remember what I was starting there or what the objective was. If I'm guessing, I think at that time I was helping do production on a script typeface—and was trying to simplify the process of lining up the connecting paths. Imagining a face with multiple variants for each glyph—your description seems to line up with that. Hope that helps!
